### ISSUE TITLE
 SyntaxError: Unexpected end of JSON input. Cropped path?

### ISSUE THREAD

**Issue by maaaaagda** [revathskumar/npm-audit-ci#14]
I have such problem while running npm audit ci command:
[10:56:50][npm run npmaudit] undefined:4610
[10:56:50][npm run npmaudit]           "path": "jest>jest-cli>@jest/core>@jest/reporters>jest-runtime>jest-config>jest-jasmine2>@jest/environment>@jest/transform>jest-
[10:56:50][npm run npmaudit]                                                                                                                                           
[10:56:50][npm run npmaudit] 
[10:56:50][npm run npmaudit] SyntaxError: Unexpected end of JSON input
[10:56:50][npm run npmaudit]     at JSON.parse (<anonymous>)
[10:56:50][npm run npmaudit]     at /opt/buildAgent/work/d8e7371ad288ec95/node_modules/npm-audit-ci/index.js:95:31
[10:56:50][npm run npmaudit]     at ChildProcess.exithandler (child_process.js:301:5)
[10:56:50][npm run npmaudit]     at ChildProcess.emit (events.js:198:13)
[10:56:50][npm run npmaudit]     at maybeClose (internal/child_process.js:982:16)
[10:56:50][npm run npmaudit]     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
![image](https://user-images.githubusercontent.com/17687646/61211758-b7fa8d00-a700-11e9-9263-f0fa32d8d0da.png)
For me it looks like the path to dependency is cropped so it's not a valid json and thus the error. Any idea how to fix this?

**Comment by revathskumar** [comment]
@maaaaagda Which version you are using? 
A similar issue is fixed recently (see #11) in the latest release.

**Comment by maaaaagda** [comment]
My bad. I had "npm-audit-ci": "^1.2.0" and was convinced that npm install is upgrading this to "^1.2.1". And this problem occurred just after your change and thought maybe this broke sth. Nevertheless it's working now so sorry for this and thanks for quick answer.
